### ISSUE TITLE
[Bug] Armory2.0 UserReport Error

### ISSUE THREAD

**Issue by jk-mayne** [depthsecurity/armory#45]
**Describe the bug**
In armory 2.0 branch the UserReport displays an error. 

**To Reproduce**
1. Have users in database from another module. 
2. Run `armory2 -r UserReport -u3`

**Error:** 
`
Traceback (most recent call last):
 File "/usr/local/bin/armory2", line 11, in <module>
    load_entry_point('depth-armory==2.0.0', 'console_scripts', 'armory2')()
  File "/usr/local/lib/python3.7/dist-packages/depth_armory-2.0.0-py3.7.egg/armory2/armory_cmd.py", line 485, in main
    run_report(Report, cmd_args, reports[0])
  File "/usr/local/lib/python3.7/dist-packages/depth_armory-2.0.0-py3.7.egg/armory2/armory_cmd.py", line 300, in run_report
    m.run(args)
  File "/usr/local/lib/python3.7/dist-packages/depth_armory-2.0.0-py3.7.egg/armory2/armory_main/included/reports/UserReport.py", line 51, in run
    qry, model = self.BaseDomain.get_query()
AttributeError: 'Report' object has no attribute 'BaseDomain'`

**Expected behavior**
Expected user emails as output. 

**Desktop:**
Docker on OS X.

**Comment by fang0654** [comment]
This should be fixed now.
